name: sync with homebrew-core
on:
  workflow_dispatch:
  schedule:
    - cron: "0 20 * * 1"
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Apply changes from homebrew-core
        id: apply
        shell: bash
        run: |
          ./sync.sh
          updated=false
          if ! git diff --exit-code; then
            updated=true
          fi
          printf 'updated=%s\n' "$updated" >> "$GITHUB_OUTPUT"
      - name: Submit PR
        if: steps.apply.outputs.updated == 'true'
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR_ID+$GITHUB_ACTOR@users.noreply.github.com"

          branch="auto-$(date --rfc-3339=date)"
          git checkout -b "$branch"
          git add --update
          git commit -m "Sync to $(cat ./homebrew_core_commit)"
          git push -u origin "$branch"
          gh pr create --fill
